package binance

const (
	V3            = "https://api.binance.us"
	PING          = "/api/v3/ping"
	KLINES        = "/api/v3/klines"
	PRICE         = "/api/v3/ticker/price"
	TIME          = "/api/v3/time"
	ORDER         = "/api/v3/order"
	BOOKTICKER    = "/api/v3/ticker/bookTicker"
	EXCHANGE_INFO = "/api/v3/exchangeInfo"
	TEST_ORDER    = "/api/v3/order/test"
	INTERVAL      = "/api/v31d"
	OPEN_ORDERS   = "/api/v3/openOrders"
	ACCT          = "/api/v3/account"
	OCO_ORDER     = "/api/v3/order/oco"
	SYSTEM_STATUS = "/sapi/v1/system/status"
	RECENT_TRADES = "/api/v3/trades"
	HIST_TRADES   = "/api/v3/historicalTrades"
	AGG_TRADES    = "/api/v3/aggTrades"
	BOOK_DEPTH    = "/api/v3/depth"
	USER_TRADES   = "/api/v3/myTrades"
	TICKER_PRICE  = "/api/v3/ticker/price"
	AVG_PRICE     = "/api/v3/avgPrice"
	BOOK_TICKER   = "/api/v3/ticker/bookTicker"
	DAY_CHANGE    = "/api/v3/ticker/24hr"
	TICKER        = "/api/v3/ticker"
	USER_DATA     = "/api/v3/userDataStream"
)
