package binance

const (
	ACCT            = "/api/v3/account"
	AGG_TRADES      = "/api/v3/aggTrades"
	ALL_ORDER_LIST  = "/api/v3/allOrderList"
	AVG_PRICE       = "/api/v3/avgPrice"
	BOOK_DEPTH      = "/api/v3/depth"
	BOOK_TICKER     = "/api/v3/ticker/bookTicker"
	DAY_CHANGE      = "/api/v3/ticker/24hr"
	EXCHANGE_INFO   = "/api/v3/exchangeInfo"
	HIST_TRADES     = "/api/v3/historicalTrades"
	KLINES          = "/api/v3/klines"
	OCO_ORDER       = "/api/v3/order/oco"
	OPEN_ORDER_LIST = "/api/v3/openOrderList"
	OPEN_ORDERS     = "/api/v3/openOrders"
	ORDER           = "/api/v3/order"
	ORDER_LIST      = "api/v3/orderList"
	PING            = "/api/v3/ping"
	PRICE           = "/api/v3/ticker/price"
	RECENT_TRADES   = "/api/v3/trades"
	SYSTEM_STATUS   = "/sapi/v1/system/status"
	TEST_ORDER      = "/api/v3/order/test"
	TICKER          = "/api/v3/ticker"
	TICKER_PRICE    = "/api/v3/ticker/price"
	TIME            = "/api/v3/time"
	USER_DATA       = "/api/v3/userDataStream"
	USER_TRADES     = "/api/v3/myTrades"
)
